services:
  django:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    env_file:
      - ../.env.dev
    
    volumes:
      - .:/app
      - static_volume:/app/static
      - ./ecowiser/media:/app/media

    depends_on:
      - redis

  redis:
    container_name: redis
    image: redis
    ports:
      - "6378:6379"

  celery:
    container_name: celery
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: celery -A ecowiser worker -l info
    volumes:
      - .:/app
      - ./ecowiser/media:/app/media
    env_file:
      - ../.env.dev
    depends_on:
      - redis

  celery-beat:
    container_name: celery_beat
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: celery -A ecowiser beat -l info
    volumes:
      - .:/app
      - ./ecowiser/media:/app/media
    depends_on:
      - redis
    env_file:
      - ../.env.dev

volumes:
  static_volume:
  media_volume: