version: "3.9"

services:
  django:
    container_name: ecowiser_backend
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - redis
  
  redis:
    container_name: ecowiser_redis
    image: redis:alpine
    ports:
      - "6378:6379"
  
  celery:
    container_name: ecowiser_celery
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: celery -A ecowiser worker -l info
    volumes:
      - .:/app
    env_file:
      - ../.env
    depends_on:
      - redis
  
  celery-beat:
    container_name: ecowiser_celery_beat
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: celery -A ecowiser beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - ../.env
