
services:
  django:
    container_name: ecowiser_backend
    image: 322680460472.dkr.ecr.us-east-1.amazonaws.com/ecowiser/backend:latest
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - redis
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    restart: always
  
  redis:
    container_name: ecowiser_redis
    image: redis:alpine
    ports:
      - "6378:6379"
  
  celery:
    container_name: ecowiser_celery
    image: 322680460472.dkr.ecr.us-east-1.amazonaws.com/ecowiser/backend:latest
    command: celery -A ecowiser worker -l info
    volumes:
      - .:/app
    env_file:
      - ../.env
    depends_on:
      - redis
  
  celery-beat:
    container_name: ecowiser_celery_beat
    image: 322680460472.dkr.ecr.us-east-1.amazonaws.com/ecowiser/backend:latest
    command: celery -A ecowiser beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - ../.env
    restart: always

  nginx:
    container_name: ecowiser_nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - django
    restart: always

volumes:
  static_volume:
  media_volume: