version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6378:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: celery -A ecowiser worker -l info
    volumes:
      - .:/app
    env_file:
      - ../.env
    depends_on:
      - redis

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: celery -A ecowiser beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - ../.env
