# Generated by Django 5.2.1 on 2025-05-31 07:59

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_remove_tenant_subscription_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_tier', models.CharField(choices=[('Free', 'Free'), ('Pro', 'Pro'), ('Enterprise', 'Enterprise')], default='Free', max_length=20)),
                ('current_cycle_start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_cycle_end_date', models.DateTimeField(default=datetime.datetime(2025, 6, 30, 7, 59, 18, 942413, tzinfo=datetime.timezone.utc))),
                ('next_subscription_tier', models.CharField(choices=[('Free', 'Free'), ('Pro', 'Pro'), ('Enterprise', 'Enterprise')], default='Free', max_length=20)),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('invoice_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('billing_end_date', models.DateTimeField(default=datetime.datetime(2025, 6, 30, 7, 59, 18, 942413, tzinfo=datetime.timezone.utc))),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='tenants.tenant')),
                ('subscription_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='billings.subscription')),
            ],
        ),
    ]
