# Generated by Django 5.2.1 on 2025-05-25 07:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_remove_tenant_subscription_tier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('bill_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billing_cycle', models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Monthly', max_length=20)),
                ('subscription_tier', models.CharField(choices=[('Free', 'Free'), ('Pro', 'Pro'), ('Enterprise', 'Enterprise')], default='Free', max_length=20)),
                ('subscription_start_date', models.DateTimeField(auto_now_add=True)),
                ('subscription_cancel_date', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='tenants.tenant')),
            ],
        ),
    ]
