# Generated by Django 5.2.1 on 2025-05-25 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='billing_cycle',
        ),
        migrations.AddField(
            model_name='billing',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 25, 10, 47, 40, 818007, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
