# Generated by Django 5.2.1 on 2025-05-25 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0002_remove_billing_billing_cycle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 25, 11, 2, 34, 329017, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='subscription_start_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 25, 11, 2, 34, 329017, tzinfo=datetime.timezone.utc)),
        ),
    ]
