# Generated by Django 5.2.1 on 2025-05-31 08:08

import billings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0002_alter_invoices_billing_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='billing_end_date',
            field=models.DateTimeField(default=billings.models.default_cycle_end_date),
        ),
        migrations.AlterField(
            model_name='invoices',
            name='billing_start_date',
            field=models.DateTimeField(default=billings.models.default_cycle_start_date),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='current_cycle_end_date',
            field=models.DateTimeField(default=billings.models.default_cycle_end_date),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='current_cycle_start_date',
            field=models.DateTimeField(default=billings.models.default_cycle_start_date),
        ),
    ]
