# Generated by Django 5.2.1 on 2025-05-25 11:03

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0003_alter_billing_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 25, 11, 3, 45, 558882, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='subscription_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
