# Generated by Django 5.2.1 on 2025-05-25 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0004_alter_billing_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 25, 14, 38, 0, 831490, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
