# Generated by Django 5.2.1 on 2025-05-25 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0008_alter_billing_subscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 25, 17, 41, 3, 168422, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
