# Generated by Django 5.2.1 on 2025-05-26 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0010_alter_billing_subscription_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 26, 11, 57, 14, 719160, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
