# Generated by Django 5.2.1 on 2025-05-27 06:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0012_subscription_invoices_delete_billing'),
        ('tenants', '0003_remove_tenant_subscription_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='billing_end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 27, 6, 55, 12, 615873, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='current_cycle_end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 27, 6, 55, 12, 614868, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='tenants.tenant'),
        ),
    ]
