# Generated by Django 5.2.1 on 2025-05-28 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billings', '0013_alter_invoices_billing_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='billing_end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 28, 17, 13, 33, 119792, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='current_cycle_end_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 28, 17, 13, 33, 119792, tzinfo=datetime.timezone.utc)),
        ),
    ]
