# Generated by Django 5.2.1 on 2025-05-24 14:31

import tenants.models
import tenants.storage
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, storage=tenants.storage.PublicLogoStorage(), upload_to=tenants.models.tenant_logo_upload_path)),
                ('subscription_tier', models.CharField(choices=[('Free', 'Free'), ('Pro', 'Pro'), ('Enterprise', 'Enterprise')], default='Free', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
