# Generated by Django 5.2.1 on 2025-05-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_remove_media_private_media_visibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
