# Generated by Django 5.2.1 on 2025-05-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_media_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
