# Generated by Django 5.2.1 on 2025-05-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_csvtables_file_size_csvtables_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='file_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video')], max_length=50, null=True),
        ),
    ]
