name: Test SSH

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test SSH to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "SSH to EC2 succeeded!"
            uname -a
